FactoryBot.create(:todo_list, :with_items, name: 'Setup Rails Application')
FactoryBot.create(:todo_list, :with_items, name: 'Setup Docker PG database')
FactoryBot.create(:todo_list, :with_items, name: 'Create todo_lists table')
FactoryBot.create(:todo_list, :with_items, name: 'Create TodoList model')
FactoryBot.create(:todo_list, :with_items, name: 'Create TodoList controller')
